

name: Publish

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # release:
  #   types: [published]

permissions:
  contents: read

jobs:
  call-test-build:
    uses: ./.github/workflows/create_artifacts.yml

  check-artifacts:
    needs: call-test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download all  artifacts
        uses: actions/download-artifact@v3
      - name: List files
        run: ls -R

  # deploy:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.x'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install build
  #   - name: Build package
  #     run: python -m build
  #   - name: Publish package
  #     uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
  #     with:
  #       user: __token__
  #       password: ${{ secrets.PYPI_API_TOKEN }}
