name: pull_request_tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Version
      run: python --version
    - name: Update Pip
      run: python -m pip install --upgrade pip
    - name: Install Build
      run: pip install build
    - name: Build packages
      run: python -m build
    - name: Install rsatoolbox
      run: pip install dist/rsatoolbox-*.tar.gz
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install test dependencies
      run: pip install -r tests/requirements.txt
    - name: Unit tests
      run: pytest
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: rsatoolbox-sdist
        path: dist/rsatoolbox-*.tar.gz
        retention-days: 1
